---
title: "Bycatch Estimation and Expansion in STAN"
author: "Eric Ward"
date: "March 21, 2017"
output:
  html_document: default
  pdf_document: default
---

## Load library

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, results="hide", message=FALSE, warning=FALSE}
require(devtools)
devtools::install_github("eric-ward/bycatch")
library(bycatch)
```

## Load data
```{r data}
# replace this with your own data frame
d = data.frame("Year"= 2002:2014, 
  "Takes" = c(0, 0, 0, 0, 0, 0, 0, 0, 1, 3, 0, 0, 0),
  "expansionRate" = c(24, 22, 14, 32, 28, 25, 30,  7, 26, 21, 22, 23, 27),
  "Sets" = c(391, 340, 330, 660, 470, 500, 330, 287, 756, 673, 532, 351, 486))
```

## Fit model

```{r, results="hide", message=FALSE, warning=FALSE}
fit = bycatch_expansion(time = d[,"Year"], events = d[,"Takes"], 
  effort = d[,"Sets"], coverage = d[,"expansionRate"])
```

## Make plots

```{r, fig.pos="placeHere", fig.cap = "Estimated fleet-level expanded bycatch, incorporating data on takes, effort, and observer coverage. Dots represent observed bycatch events."}
plot_expanded(fit, xlab="Year", ylab = "Fleet-level bycatch")
```

## Make table of expanded bycatch estimates

```{r, eval=FALSE}
df = data.frame("time" = d[,"Year"], 
  "mean" = apply(fit$expanded_estimates, 2, mean),
  "median" = apply(fit$expanded_estimates, 2, quantile, 0.5),
  "lower95" = apply(fit$expanded_estimates, 2, quantile, 0.025),
  "upper95" = apply(fit$expanded_estimates, 2, quantile, 0.975))

write.table(df, "estimated_bycatch.csv", row.names=F, col.names=T, sep=",")
```
