/*
    bycatch is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    bycatch is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with bycatch.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.21.0

#include <stan/model/model_header.hpp>

namespace model_bycatch_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_bycatch");
    reader.add_event(74, 72, "end", "model_bycatch");
    return reader;
}

class model_bycatch
  : public stan::model::model_base_crtp<model_bycatch> {
private:
        int n_row;
        vector_d effort;
        std::vector<int> yint;
        std::vector<int> time;
        int n_year;
        int K;
        matrix_d x;
        int family;
        int time_varying;
public:
    model_bycatch(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_bycatch(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : model_base_crtp(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_bycatch_namespace::model_bycatch";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {
            // initialize data block variables from context__
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "n_row", "int", context__.to_vec());
            n_row = int(0);
            vals_i__ = context__.vals_i("n_row");
            pos__ = 0;
            n_row = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_row", n_row, 0);

            current_statement_begin__ = 3;
            validate_non_negative_index("effort", "n_row", n_row);
            context__.validate_dims("data initialization", "effort", "vector_d", context__.to_vec(n_row));
            effort = Eigen::Matrix<double, Eigen::Dynamic, 1>(n_row);
            vals_r__ = context__.vals_r("effort");
            pos__ = 0;
            size_t effort_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < effort_j_1_max__; ++j_1__) {
                effort(j_1__) = vals_r__[pos__++];
            }

            current_statement_begin__ = 4;
            validate_non_negative_index("yint", "n_row", n_row);
            context__.validate_dims("data initialization", "yint", "int", context__.to_vec(n_row));
            yint = std::vector<int>(n_row, int(0));
            vals_i__ = context__.vals_i("yint");
            pos__ = 0;
            size_t yint_k_0_max__ = n_row;
            for (size_t k_0__ = 0; k_0__ < yint_k_0_max__; ++k_0__) {
                yint[k_0__] = vals_i__[pos__++];
            }

            current_statement_begin__ = 5;
            validate_non_negative_index("time", "n_row", n_row);
            context__.validate_dims("data initialization", "time", "int", context__.to_vec(n_row));
            time = std::vector<int>(n_row, int(0));
            vals_i__ = context__.vals_i("time");
            pos__ = 0;
            size_t time_k_0_max__ = n_row;
            for (size_t k_0__ = 0; k_0__ < time_k_0_max__; ++k_0__) {
                time[k_0__] = vals_i__[pos__++];
            }

            current_statement_begin__ = 6;
            context__.validate_dims("data initialization", "n_year", "int", context__.to_vec());
            n_year = int(0);
            vals_i__ = context__.vals_i("n_year");
            pos__ = 0;
            n_year = vals_i__[pos__++];
            check_greater_or_equal(function__, "n_year", n_year, 0);

            current_statement_begin__ = 7;
            context__.validate_dims("data initialization", "K", "int", context__.to_vec());
            K = int(0);
            vals_i__ = context__.vals_i("K");
            pos__ = 0;
            K = vals_i__[pos__++];
            check_greater_or_equal(function__, "K", K, 0);

            current_statement_begin__ = 8;
            validate_non_negative_index("x", "n_row", n_row);
            validate_non_negative_index("x", "K", K);
            context__.validate_dims("data initialization", "x", "matrix_d", context__.to_vec(n_row,K));
            x = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic>(n_row, K);
            vals_r__ = context__.vals_r("x");
            pos__ = 0;
            size_t x_j_2_max__ = K;
            size_t x_j_1_max__ = n_row;
            for (size_t j_2__ = 0; j_2__ < x_j_2_max__; ++j_2__) {
                for (size_t j_1__ = 0; j_1__ < x_j_1_max__; ++j_1__) {
                    x(j_1__, j_2__) = vals_r__[pos__++];
                }
            }

            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "family", "int", context__.to_vec());
            family = int(0);
            vals_i__ = context__.vals_i("family");
            pos__ = 0;
            family = vals_i__[pos__++];

            current_statement_begin__ = 10;
            context__.validate_dims("data initialization", "time_varying", "int", context__.to_vec());
            time_varying = int(0);
            vals_i__ = context__.vals_i("time_varying");
            pos__ = 0;
            time_varying = vals_i__[pos__++];


            // initialize transformed data variables
            // execute transformed data statements

            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 13;
            validate_non_negative_index("beta", "K", K);
            num_params_r__ += K;
            current_statement_begin__ = 14;
            validate_non_negative_index("est_time_dev", "(time_varying * (n_year - 1))", (time_varying * (n_year - 1)));
            num_params_r__ += (time_varying * (n_year - 1));
            current_statement_begin__ = 15;
            validate_non_negative_index("sigma_rw", "time_varying", time_varying);
            num_params_r__ += (1 * time_varying);
            current_statement_begin__ = 16;
            validate_non_negative_index("nb2_phi", "family", family);
            num_params_r__ += (1 * family);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_bycatch() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        current_statement_begin__ = 13;
        if (!(context__.contains_r("beta")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable beta missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("beta");
        pos__ = 0U;
        validate_non_negative_index("beta", "K", K);
        context__.validate_dims("parameter initialization", "beta", "vector_d", context__.to_vec(K));
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta(K);
        size_t beta_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            beta(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(beta);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable beta: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 14;
        if (!(context__.contains_r("est_time_dev")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable est_time_dev missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("est_time_dev");
        pos__ = 0U;
        validate_non_negative_index("est_time_dev", "(time_varying * (n_year - 1))", (time_varying * (n_year - 1)));
        context__.validate_dims("parameter initialization", "est_time_dev", "vector_d", context__.to_vec((time_varying * (n_year - 1))));
        Eigen::Matrix<double, Eigen::Dynamic, 1> est_time_dev((time_varying * (n_year - 1)));
        size_t est_time_dev_j_1_max__ = (time_varying * (n_year - 1));
        for (size_t j_1__ = 0; j_1__ < est_time_dev_j_1_max__; ++j_1__) {
            est_time_dev(j_1__) = vals_r__[pos__++];
        }
        try {
            writer__.vector_unconstrain(est_time_dev);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable est_time_dev: ") + e.what()), current_statement_begin__, prog_reader__());
        }

        current_statement_begin__ = 15;
        if (!(context__.contains_r("sigma_rw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma_rw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma_rw");
        pos__ = 0U;
        validate_non_negative_index("sigma_rw", "time_varying", time_varying);
        context__.validate_dims("parameter initialization", "sigma_rw", "double", context__.to_vec(time_varying));
        std::vector<double> sigma_rw(time_varying, double(0));
        size_t sigma_rw_k_0_max__ = time_varying;
        for (size_t k_0__ = 0; k_0__ < sigma_rw_k_0_max__; ++k_0__) {
            sigma_rw[k_0__] = vals_r__[pos__++];
        }
        size_t sigma_rw_i_0_max__ = time_varying;
        for (size_t i_0__ = 0; i_0__ < sigma_rw_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, sigma_rw[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma_rw: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }

        current_statement_begin__ = 16;
        if (!(context__.contains_r("nb2_phi")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable nb2_phi missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("nb2_phi");
        pos__ = 0U;
        validate_non_negative_index("nb2_phi", "family", family);
        context__.validate_dims("parameter initialization", "nb2_phi", "double", context__.to_vec(family));
        std::vector<double> nb2_phi(family, double(0));
        size_t nb2_phi_k_0_max__ = family;
        for (size_t k_0__ = 0; k_0__ < nb2_phi_k_0_max__; ++k_0__) {
            nb2_phi[k_0__] = vals_r__[pos__++];
        }
        size_t nb2_phi_i_0_max__ = family;
        for (size_t i_0__ = 0; i_0__ < nb2_phi_i_0_max__; ++i_0__) {
            try {
                writer__.scalar_lb_unconstrain(0, nb2_phi[i_0__]);
            } catch (const std::exception& e) {
                stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable nb2_phi: ") + e.what()), current_statement_begin__, prog_reader__());
            }
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);

            // model parameters
            current_statement_begin__ = 13;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> beta;
            (void) beta;  // dummy to suppress unused var warning
            if (jacobian__)
                beta = in__.vector_constrain(K, lp__);
            else
                beta = in__.vector_constrain(K);

            current_statement_begin__ = 14;
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> est_time_dev;
            (void) est_time_dev;  // dummy to suppress unused var warning
            if (jacobian__)
                est_time_dev = in__.vector_constrain((time_varying * (n_year - 1)), lp__);
            else
                est_time_dev = in__.vector_constrain((time_varying * (n_year - 1)));

            current_statement_begin__ = 15;
            std::vector<local_scalar_t__> sigma_rw;
            size_t sigma_rw_d_0_max__ = time_varying;
            sigma_rw.reserve(sigma_rw_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < sigma_rw_d_0_max__; ++d_0__) {
                if (jacobian__)
                    sigma_rw.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    sigma_rw.push_back(in__.scalar_lb_constrain(0));
            }

            current_statement_begin__ = 16;
            std::vector<local_scalar_t__> nb2_phi;
            size_t nb2_phi_d_0_max__ = family;
            nb2_phi.reserve(nb2_phi_d_0_max__);
            for (size_t d_0__ = 0; d_0__ < nb2_phi_d_0_max__; ++d_0__) {
                if (jacobian__)
                    nb2_phi.push_back(in__.scalar_lb_constrain(0, lp__));
                else
                    nb2_phi.push_back(in__.scalar_lb_constrain(0));
            }

            // transformed parameters
            current_statement_begin__ = 19;
            validate_non_negative_index("lambda", "n_row", n_row);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> lambda(n_row);
            stan::math::initialize(lambda, DUMMY_VAR__);
            stan::math::fill(lambda, DUMMY_VAR__);

            current_statement_begin__ = 20;
            validate_non_negative_index("pred", "n_row", n_row);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> pred(n_row);
            stan::math::initialize(pred, DUMMY_VAR__);
            stan::math::fill(pred, DUMMY_VAR__);

            current_statement_begin__ = 21;
            validate_non_negative_index("time_dev", "(time_varying * n_year)", (time_varying * n_year));
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> time_dev((time_varying * n_year));
            stan::math::initialize(time_dev, DUMMY_VAR__);
            stan::math::fill(time_dev, DUMMY_VAR__);

            // transformed parameters block statements
            current_statement_begin__ = 22;
            stan::math::assign(pred, multiply(x, beta));
            current_statement_begin__ = 24;
            if (as_bool(logical_eq(time_varying, 1))) {

                current_statement_begin__ = 25;
                stan::model::assign(time_dev, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable time_dev");
                current_statement_begin__ = 26;
                for (int i = 2; i <= n_year; ++i) {

                    current_statement_begin__ = 27;
                    stan::model::assign(time_dev, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                get_base1(est_time_dev, (i - 1), "est_time_dev", 1), 
                                "assigning variable time_dev");
                }
            }
            current_statement_begin__ = 31;
            for (int i = 1; i <= n_row; ++i) {

                current_statement_begin__ = 32;
                if (as_bool(logical_eq(time_varying, 1))) {

                    current_statement_begin__ = 33;
                    stan::model::assign(pred, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (get_base1(pred, i, "pred", 1) + (time_varying * get_base1(time_dev, get_base1(time, i, "time", 1), "time_dev", 1))), 
                                "assigning variable pred");
                }
                current_statement_begin__ = 35;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::math::exp((get_base1(pred, i, "pred", 1) + stan::math::log(get_base1(effort, i, "effort", 1)))), 
                            "assigning variable lambda");
            }

            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            current_statement_begin__ = 19;
            size_t lambda_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(lambda(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: lambda" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable lambda: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 20;
            size_t pred_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < pred_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(pred(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: pred" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable pred: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 21;
            size_t time_dev_j_1_max__ = (time_varying * n_year);
            for (size_t j_1__ = 0; j_1__ < time_dev_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(time_dev(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: time_dev" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable time_dev: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }

            // model body

            current_statement_begin__ = 39;
            lp_accum__.add(student_t_log<propto__>(beta, 3, 0, 2));
            current_statement_begin__ = 41;
            if (as_bool(logical_eq(time_varying, 1))) {

                current_statement_begin__ = 42;
                lp_accum__.add(student_t_log<propto__>(sigma_rw, 3, 0, 1));
                current_statement_begin__ = 43;
                lp_accum__.add(student_t_log<propto__>(get_base1(est_time_dev, 1, "est_time_dev", 1), 3, 0, 2));
                current_statement_begin__ = 44;
                for (int i = 2; i <= (n_year - 1); ++i) {

                    current_statement_begin__ = 46;
                    lp_accum__.add(normal_log<propto__>(get_base1(est_time_dev, i, "est_time_dev", 1), get_base1(est_time_dev, (i - 1), "est_time_dev", 1), get_base1(sigma_rw, 1, "sigma_rw", 1)));
                }
            }
            current_statement_begin__ = 50;
            if (as_bool(logical_eq(family, 0))) {

                current_statement_begin__ = 51;
                for (int i = 1; i <= n_row; ++i) {

                    current_statement_begin__ = 52;
                    lp_accum__.add(poisson_log<propto__>(get_base1(yint, i, "yint", 1), get_base1(lambda, i, "lambda", 1)));
                }
            } else {

                current_statement_begin__ = 55;
                lp_accum__.add(student_t_log<propto__>(nb2_phi, 3, 0, 2));
                current_statement_begin__ = 56;
                for (int i = 1; i <= n_row; ++i) {

                    current_statement_begin__ = 57;
                    lp_accum__.add(neg_binomial_2_log<propto__>(get_base1(yint, i, "yint", 1), get_base1(lambda, i, "lambda", 1), get_base1(nb2_phi, 1, "nb2_phi", 1)));
                }
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("beta");
        names__.push_back("est_time_dev");
        names__.push_back("sigma_rw");
        names__.push_back("nb2_phi");
        names__.push_back("lambda");
        names__.push_back("pred");
        names__.push_back("time_dev");
        names__.push_back("log_lik");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(K);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((time_varying * (n_year - 1)));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(time_varying);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(family);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_row);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_row);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back((time_varying * n_year));
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(n_row);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_bycatch_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning

        // read-transform, write parameters
        Eigen::Matrix<double, Eigen::Dynamic, 1> beta = in__.vector_constrain(K);
        size_t beta_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            vars__.push_back(beta(j_1__));
        }

        Eigen::Matrix<double, Eigen::Dynamic, 1> est_time_dev = in__.vector_constrain((time_varying * (n_year - 1)));
        size_t est_time_dev_j_1_max__ = (time_varying * (n_year - 1));
        for (size_t j_1__ = 0; j_1__ < est_time_dev_j_1_max__; ++j_1__) {
            vars__.push_back(est_time_dev(j_1__));
        }

        std::vector<double> sigma_rw;
        size_t sigma_rw_d_0_max__ = time_varying;
        sigma_rw.reserve(sigma_rw_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < sigma_rw_d_0_max__; ++d_0__) {
            sigma_rw.push_back(in__.scalar_lb_constrain(0));
        }
        size_t sigma_rw_k_0_max__ = time_varying;
        for (size_t k_0__ = 0; k_0__ < sigma_rw_k_0_max__; ++k_0__) {
            vars__.push_back(sigma_rw[k_0__]);
        }

        std::vector<double> nb2_phi;
        size_t nb2_phi_d_0_max__ = family;
        nb2_phi.reserve(nb2_phi_d_0_max__);
        for (size_t d_0__ = 0; d_0__ < nb2_phi_d_0_max__; ++d_0__) {
            nb2_phi.push_back(in__.scalar_lb_constrain(0));
        }
        size_t nb2_phi_k_0_max__ = family;
        for (size_t k_0__ = 0; k_0__ < nb2_phi_k_0_max__; ++k_0__) {
            vars__.push_back(nb2_phi[k_0__]);
        }

        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        if (!include_tparams__ && !include_gqs__) return;

        try {
            // declare and define transformed parameters
            current_statement_begin__ = 19;
            validate_non_negative_index("lambda", "n_row", n_row);
            Eigen::Matrix<double, Eigen::Dynamic, 1> lambda(n_row);
            stan::math::initialize(lambda, DUMMY_VAR__);
            stan::math::fill(lambda, DUMMY_VAR__);

            current_statement_begin__ = 20;
            validate_non_negative_index("pred", "n_row", n_row);
            Eigen::Matrix<double, Eigen::Dynamic, 1> pred(n_row);
            stan::math::initialize(pred, DUMMY_VAR__);
            stan::math::fill(pred, DUMMY_VAR__);

            current_statement_begin__ = 21;
            validate_non_negative_index("time_dev", "(time_varying * n_year)", (time_varying * n_year));
            Eigen::Matrix<double, Eigen::Dynamic, 1> time_dev((time_varying * n_year));
            stan::math::initialize(time_dev, DUMMY_VAR__);
            stan::math::fill(time_dev, DUMMY_VAR__);

            // do transformed parameters statements
            current_statement_begin__ = 22;
            stan::math::assign(pred, multiply(x, beta));
            current_statement_begin__ = 24;
            if (as_bool(logical_eq(time_varying, 1))) {

                current_statement_begin__ = 25;
                stan::model::assign(time_dev, 
                            stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                            0, 
                            "assigning variable time_dev");
                current_statement_begin__ = 26;
                for (int i = 2; i <= n_year; ++i) {

                    current_statement_begin__ = 27;
                    stan::model::assign(time_dev, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                get_base1(est_time_dev, (i - 1), "est_time_dev", 1), 
                                "assigning variable time_dev");
                }
            }
            current_statement_begin__ = 31;
            for (int i = 1; i <= n_row; ++i) {

                current_statement_begin__ = 32;
                if (as_bool(logical_eq(time_varying, 1))) {

                    current_statement_begin__ = 33;
                    stan::model::assign(pred, 
                                stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                                (get_base1(pred, i, "pred", 1) + (time_varying * get_base1(time_dev, get_base1(time, i, "time", 1), "time_dev", 1))), 
                                "assigning variable pred");
                }
                current_statement_begin__ = 35;
                stan::model::assign(lambda, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            stan::math::exp((get_base1(pred, i, "pred", 1) + stan::math::log(get_base1(effort, i, "effort", 1)))), 
                            "assigning variable lambda");
            }

            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // write transformed parameters
            if (include_tparams__) {
                size_t lambda_j_1_max__ = n_row;
                for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                    vars__.push_back(lambda(j_1__));
                }
                size_t pred_j_1_max__ = n_row;
                for (size_t j_1__ = 0; j_1__ < pred_j_1_max__; ++j_1__) {
                    vars__.push_back(pred(j_1__));
                }
                size_t time_dev_j_1_max__ = (time_varying * n_year);
                for (size_t j_1__ = 0; j_1__ < time_dev_j_1_max__; ++j_1__) {
                    vars__.push_back(time_dev(j_1__));
                }
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 62;
            validate_non_negative_index("log_lik", "n_row", n_row);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(n_row);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);

            // generated quantities statements
            current_statement_begin__ = 63;
            if (as_bool(logical_eq(family, 0))) {

                current_statement_begin__ = 64;
                for (int n = 1; n <= n_row; ++n) {

                    current_statement_begin__ = 65;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                                poisson_log(get_base1(yint, n, "yint", 1), get_base1(lambda, n, "lambda", 1)), 
                                "assigning variable log_lik");
                }
            } else {

                current_statement_begin__ = 68;
                for (int n = 1; n <= n_row; ++n) {

                    current_statement_begin__ = 69;
                    stan::model::assign(log_lik, 
                                stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                                neg_binomial_2_log(get_base1(yint, n, "yint", 1), get_base1(lambda, n, "lambda", 1), get_base1(nb2_phi, 1, "nb2_phi", 1)), 
                                "assigning variable log_lik");
                }
            }

            // validate, write generated quantities
            current_statement_begin__ = 62;
            size_t log_lik_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    std::string model_name() const {
        return "model_bycatch";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t est_time_dev_j_1_max__ = (time_varying * (n_year - 1));
        for (size_t j_1__ = 0; j_1__ < est_time_dev_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "est_time_dev" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_rw_k_0_max__ = time_varying;
        for (size_t k_0__ = 0; k_0__ < sigma_rw_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_rw" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nb2_phi_k_0_max__ = family;
        for (size_t k_0__ = 0; k_0__ < nb2_phi_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nb2_phi" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t lambda_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t pred_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < pred_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "pred" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t time_dev_j_1_max__ = (time_varying * n_year);
            for (size_t j_1__ = 0; j_1__ < time_dev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "time_dev" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n_row;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        size_t beta_j_1_max__ = K;
        for (size_t j_1__ = 0; j_1__ < beta_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "beta" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t est_time_dev_j_1_max__ = (time_varying * (n_year - 1));
        for (size_t j_1__ = 0; j_1__ < est_time_dev_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "est_time_dev" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t sigma_rw_k_0_max__ = time_varying;
        for (size_t k_0__ = 0; k_0__ < sigma_rw_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "sigma_rw" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t nb2_phi_k_0_max__ = family;
        for (size_t k_0__ = 0; k_0__ < nb2_phi_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "nb2_phi" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
            size_t lambda_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < lambda_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "lambda" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t pred_j_1_max__ = n_row;
            for (size_t j_1__ = 0; j_1__ < pred_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "pred" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            size_t time_dev_j_1_max__ = (time_varying * n_year);
            for (size_t j_1__ = 0; j_1__ < time_dev_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "time_dev" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
        }

        if (!include_gqs__) return;
        size_t log_lik_j_1_max__ = n_row;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }

}; // model

}  // namespace

typedef model_bycatch_namespace::model_bycatch stan_model;

#ifndef USING_R

stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

#endif


#endif
